Проект посмотри в окно
Lyapo4ka/posmotri_v_okno pull request #1
Opened 2024-10-11 09:54 UTC by Lyapo4ka

2024-10-11 11:00 UTC, seginel requested changes
Здравствуйте, у вас получилась достойная работа, но в ней есть замечания - здесь понадобятся доработки.
 Вы справитесь, желаю вам успехов.

### Что понравилось

* Аккуратное форматирование кода
* Абсолютное позиционирование не используется без необходимости;
* Для стилизации интерактивных элементов используется  `outline`;
* Для построения элементов использованы flex/grid.
* Заданы все состояния для интерактивных элементов из макета
* Сброшены состояния `:focus` у интерактивных элементов

### Что нужно поправить

* Все комментарии "Надо исправить" в коде.
* В проекте есть расхождения с макетом. Страница визуально должна соответствовать макету. Отличие не должно превышать 5px по вертикали и 3px по горизонтали. Для доводки вёрстки рекомендую использовать плагин [Pixel Perfect](https://www.welldonecode.com/perfectpixel/){target="_blank"}
    * Лишние бордеры:  https://disk.yandex.ru/i/xTJH3401U0bLFA
* Стоит напомнить, что все замечания не придумываются ревьюером на ходу. Они формируются на основе чеклиста и брифа к заданию. Если соблюсти все требования чеклиста и рекомендаций в брифе, то работа будет сразу же принята. Поэтому перед отправкой на следующую итерацию рекомендую самостоятельно пройтись по брифу и чеклисту и при необходимости поправить все проблемные места. Это позволит быстрее принять работу.

### Что можно лучше

* Все комментарии "Можно лучше" в коде.
* При написании CSS-правил старайтесь, чтобы они были расположены в примерном соответствии с позицией элементов в DOM

Комментарии "можно лучше" носят рекомендательный характер, их выполнение остается на Ваше усмотрение. Комментарии "надо исправить" являются обязательными, при выполнении всех "надо исправить" работа будет зачтена. Удачи

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +  background-color: #1b1919;
Надо исправить 
Фон у поля ввода должен быть прозрачным.

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +  appearance: none;
Отлично - использован трюк со свойством appearance, чтобы привести поле ввода к общему виду во всех браузерах.

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +  overflow-y: auto;
Отлично - полоса прокрутки отображается только когда контейнер переполнен элементами.

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +  overflow-x: hidden;
Обрезать здесь ничего не нужно. Используйте значение `auto`. Если при этом в правой колонке появится горизонтальная полоса прокрутки - значит нужно поправить стили, чтобы эта полоса не отображалась, но без принудительной обрезки содержимого

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +  object-fit: cover;
Отлично - видео будет занимать всю доступную область и не будет искажаться.

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +  font-weight: 700;
Надо исправить.
Проверьте параметры шрифта по макету

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +  background-color: #1b1919;
Надо исправить
Проверьте значение свойства по макету

В статичном состоянии кнопка должна быть прозрачной

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +.content__card-link_current {
Отлично - указан стиль для текущей выбранной карточки

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +.search-form__checkbox:hover {
Надо исправить
1) Чекбокс скрыт и не отображается - для него нет смысла добавлять стили 
2) У чекбокса нет элементов, у которых могло бы появиться подчёркивание (даже в случае, если бы чекбокс отобразился на экране)

Стиль нужно удалить

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +.result__video-container {
Селекторы не должны дублироваться в стилях

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +.search-form__label-text:focus {
Надо исправить
Фокус бывает только интерактивных элементов: ссылки, кнопки, элементы формы.

span не является интерактивным, поэтому этот стиль не сработает. Его нужно удалить

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +.search-form__label:focus {
Надо исправить
Фокус бывает только интерактивных элементов: ссылки, кнопки, элементы формы.

лейбл не является интерактивным, поэтому этот стиль не сработает. Его нужно удалить

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +.search-form__textfield:focus {
Отлично - у инпута сброшен фокус

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +  width: 711px;
Можно лучше 
В теоретической части вы ознакомились с логической моделью представления потока. Данная проектная работа - это отличная возможность потренироваться в использовании логических свойств. Поэтому здесь и ниже можно попробовать заменить все физические свойства логическими.

2024-10-11 11:00 UTC, seginel commented on styles/style.css
> +.content__video-card-title {
Название города может быть длинным, необходимо предусмотреть большое кол-во текста в блоке . Одним из возможных решений в данной ситуации может быть добавление в стили соответствующего элемента таких свойств `text-overflow: ellipsis; white-space: nowrap; overflow: hidden;` и ограничение максимальной ширины как в макете.

Это исправление поможет решить расхождение с макетом: https://disk.yandex.ru/i/PZV6xiy9UwUSOA 
По макету все изображения должны лежать на одной вертикальной линии.

2024-10-13 09:04 UTC, Lyapo4ka commented on styles/style.css
> +.content__video-card-title {
Сделала так, но почему-то правильно отображается только когда включаешь консоль разработчика...

2024-10-13 09:16 UTC, Lyapo4ka commented
Внесла правки. Максимальная ширина для названия городов сработала только когда я убрала скролл стилями.

2024-10-13 16:51 UTC, seginel approved these changes
Спасибо за правки. Вы внесли исправления по всем замечаниям и хочу поздравить - Вы отлично справились с выполнением проектной работы. По странице осталось одно замечание - отметил его в коде. В остальном, страница соответствует макету и требованиям чеклиста. По условиям ревью работу принимаю даже с критичным замечанием. 
Удачи в дальнейшем обучении.

2024-10-13 16:51 UTC, seginel commented on styles/style.css
> +::-webkit-scrollbar {
Надо исправить: полосу прокрутки удалять не нужно. Пользователь должен видеть, что правая колонка переполнена и её можно прокрутить, чтобы увидеть остальные элементы. 
Если при этом в правой колонке появляется горизонтальная полоса прокрутки, то в качестве решения стоит немного уменьшить значение для ограничения ширины заголовка `.content__video-card-title`

2024-10-14 10:09 UTC, merged